---
new_page_extension: md
auto_deploy: false
admin_path: "/admins"
webhook_url: 
sections:
- type: directory
  path: windows
  label: Windows
  create: all
  match: "**/*"
- type: directory
  path: unity
  label: Unity
  create: all
  match: "**/*"
- type: directory
  path: rest-api
  label: REST API
  create: all
  match: "**/*"
- type: directory
  path: react-native-bridge
  label: React-Native Bridge
  create: all
  match: "**/*"
- type: directory
  path: mobile-usecases
  label: Usecase
  create: all
  match: "**/*"
- type: directory
  path: javascript
  label: Javascript Web SDK
  create: all
  match: "**/*"
- type: directory
  path: guides
  label: Guides
  create: all
  match: "**/*"
- type: directory
  path: glossary
  label: Glossary
  create: all
  match: "**/*"
- type: directory
  path: flutter
  label: Flutter
  create: all
  match: "**/*"
- type: directory
  path: faq
  label: F&Q
  create: all
  match: "**/*"
- type: directory
  path: cordova
  label: Cordova
  create: all
  match: "**/*"
- type: directory
  path: panel
  label: Panel
  create: all
  match: "**/*"
- type: directory
  path: ios
  label: iOS
  create: all
  match: "**/*"
- type: directory
  path: android
  label: Android
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: rm -rf Gemfile.lock && mv Gemfile-dev Gemfile && bundle
    install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
